version: "3.8"
services:
    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database

    # phpmyadmin Service
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            - PMA_HOST=database
            - PMA_PORT=3306
        depends_on:
            - database

    # Database Server
    database:
        image: docker.io/bitnami/mariadb:10.6
        ports:
            - 3306:3306
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            # ALLOW_EMPTY_PASSWORD for development only
        volumes:
            - db-data:/var/lib/mariadb

    # Node Server
    node:
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true

volumes:
    db-data: ~
